routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');

//Route::get('/admin/employee/add_employee', 'EmployeeController@create')->name('add_employee');

//Route::get('/admin/employee/show_employee','EmployeeController@show_employee')->name('show_employee');

//Route::resource('admin/employee/show_employee/action', 'EmployeeController');

Route::resource('employees', 'EmployeeController');

//Route::put('employees/{id}', 'EmployeeController@edit');
Route::get('employees/getprovincia/{id}', 'EmployeeController@getDistrito');

app/Models/ModelDistrict.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ModelDistrict extends Model
{
    protected $table ="districts";

}

app/Models/ModelEmployee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ModelEmployee extends Model
{
    protected $table ="employees";
    protected $fillable = ['nome','apelido','data_nascimento','provincia_nascimento','distrito_nascimento','nacionalidade','sexo','nr_bi','nr_passaporte','nr_nuit','contacto','email'];
}

app/Models/ModelProvince.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ModelProvince extends Model
{
    protected $table ="provinces";
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreUpdateEmployeeRequest;
use App\Models\ModelDistrict;
use App\Models\ModelEmployee;
use App\Models\ModelProvince;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{

    private $objEmployee;
    private $objProvince;

    public function __construct(){

        $this->objEmployee = new ModelEmployee();
        $this->objProvince = new ModelProvince();

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function getDistrito($id)
    {
        $distritos = ModelDistrict::where('province_id', $id)->get();

        return response()->json([
            'success' => true,
            'data' => $distritos
        ]);
    }

    public function index()
    {

        $employee = $this->objEmployee->all();
        return view('admin.employee.index',compact('employee'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $employee=$this->objEmployee->all();
        $provinces = $this->objProvince->all();

        return view('admin.employee.create',compact('employee','provinces'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUpdateEmployeeRequest $request)
    {

        $salvar=$this->objEmployee->create([
            'nome'=>$request->nome,
            'apelido'=>$request->apelido,
            'data_nascimento'=>$request->data_nascimento,
            'provincia_nascimento'=>$request->provincia_nascimento,
            'distrito_nascimento'=>$request->distrito_nascimento,
            'nacionalidade'=>$request->nacionalidade,
            'sexo'=>$request->sexo,
            'nr_bi'=>$request->nr_bi,
            'nr_passaporte'=>$request->nr_passaporte,
            'nr_nuit'=>$request->nr_nuit,
            'contacto'=>$request->contacto,
            'email'=>$request->email
        ]);
        if($salvar){
            return redirect()->route('employees.index')->with('success', 'Adicionado com sucesso!');
        }else{
            return redirect()->back()->with('error', 'nao ... com sucesso!');

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       // echo $id;

      $employee=$this->objEmployee->find($id);

      return view('admin.employee.show',compact('employee'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee = $this->objEmployee->find($id);
        $provinces = $this->objProvince->all();

        return view('admin.employee.edit',compact('employee','provinces'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $editar = $this->objEmployee->where(['id'=>$id])->update([
            'nome'=>$request->nome,
            'apelido'=>$request->apelido,
            'data_nascimento'=>$request->data_nascimento,
            'provincia_nascimento'=>$request->provincia_nascimento,
            'distrito_nascimento'=>$request->distrito_nascimento,
            'nacionalidade'=>$request->nacionalidade,
            'sexo'=>$request->sexo,
            'nr_bi'=>$request->nr_bi,
            'nr_passaporte'=>$request->nr_passaporte,
            'nr_nuit'=>$request->nr_nuit,
            'contacto'=>$request->contacto,
            'email'=>$request->email
        ]);
        if($editar){
            return redirect()->route('employees.index')->with('success', 'Editado com sucesso!');
        }else{
            return redirect()->back()->with('error', 'nao ... com sucesso!');

        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $del = $this->objEmployee->destroy($id);
        return($del)?"Sim":"Não";
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/admin/employee/create.blade.php
@extends('layouts.admin')


@section('content')

<div class="main-card mb-3 card">
    <div class="card-body">
       <h5>Fucionario</h5>
        <form class="needs-validation" novalidate method="POST" action="/employees">
            @csrf
            <div class="form-row">
                <div class="col-md-4 mb-3">
                    <label for="validationCustom01">Nome Completo</label>
                <input type="text" class="form-control" id="validationCustom01" name="nome" value="{{old('nome')}}" placeholder="Nome Completo" required>
                         @error('nome')
                            <span style="color: red">{{$message}}</span>
                        @enderror
                </div>
                <div class="col-md-4 mb-3">
                    <label for="validationCustom02">Apelido</label>
                <input type="text" class="form-control" id="validationCustom02"  name ="apelido" value="{{old('apelido')}}" placeholder="Apelido" required>
                        @error('apelido')
                            <span style="color: red">{{$message}}</span>
                        @enderror
                </div>
                <div class="col-md-4 mb-3">
                    <label for="validationCustomUsername">Data de nascimento</label>

                <input type="date" class="form-control" id="validationCustomUsername" name="data_nascimento" value="{{old('data_nascimento')}}"  required>
                            @error('data_nascimento')
                                <span style="color: red">{{$message}}</span>
                            @enderror

                </div>
                 <div class="col-md-4 mb-6">
                    <div class="position-relative form-group"><label for="exampleSelect" class="">Provincia de nascimento</label>
                    <select name="provincia_nascimento" id="province_id" class="form-control" required>
                            <option>Provincia</option>
                            @foreach ($provinces as $province)
                                <option value="{{$province->id}}-{{$province->nome}}">{{$province->nome}}</option>
                            @endforeach
                        </select>
                            @error('provincia_nascimento')
                                <span style="color: red">{{$message}}</span>
                            @enderror
                    </div>
                </div>
                <div class="col-md-4 mb-6">
                    <div class="position-relative form-group"><label for="exampleSelect" class="">Distrito de nascimento</label>
                    <select name="distrito_nascimento" id="getdistrict" class="form-control" required>

                        </select>
                            @error('distrito_nascimento')
                                <span style="color: red">{{$message}}</span>
                            @enderror
                    </div>
                </div>
                <div class="col-md-4 mb-6">
                    <label for="validationCustom03">Nacionalidade</label>
                <input type="text" class="form-control" id="validationCustom03" name="nacionalidade" value="{{old('nacionalidade')}}" placeholder="Nacionalidade" required>
                        @error('nacionalidade')
                            <span style="color: red">{{$message}}</span>
                        @enderror
                </div>
            </div>
            <div class="form-row">

                <div class="col-md-3 mb-3">
                    <div class="position-relative form-group"><label for="exampleSelect" class="">Sexo</label>
                    <select name="sexo" value="{{old('sexo')}}" id="exampleSelect" class="form-control">
                            <option>Masculino</option>
                            <option>Femenino</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-3 mb-3">
                    <label for="validationCustom05">BI Nº</label>
                <input type="text" class="form-control" id="validationCustom05" name="nr_bi" value="{{old('nr_bi')}}" placeholder="Numero de BI" required>
                         @error('nr_bi')
                            <span style="color: red">{{$message}}</span>
                        @enderror
                </div>
                <div class="col-md-3 mb-3">
                    <label for="validationCustom05">Passaporte Nº</label>
                <input type="text" class="form-control" id="validationCustom05" name="nr_passaporte" value="{{old('nr_passaporte')}}" placeholder="Numero de Passaporte" required>
                         @error('nr_passaporte')
                            <span style="color: red">{{$message}}</span>
                        @enderror
                </div>
                <div class="col-md-3 mb-3">
                    <label for="validationCustom05">Nuit Nº</label>
                <input type="text" class="form-control" id="validationCustom05" name="nr_nuit" value="{{old('nr_nuit')}}" placeholder="Numero de Nuit" required>
                        @error('nr_nuit')
                            <span style="color: red">{{$message}}</span>
                        @enderror
                </div>
                <div class="col-md-4 mb-3">
                    <label for="validationCustom05">Contacto</label>
                <input type="text" class="form-control" id="validationCustom05" name="contacto" value="{{old('contacto')}}" placeholder="Numero de Contacto" required>
                         @error('contacto')
                            <span style="color: red">{{$message}}</span>
                        @enderror
                </div>
                <div class="col-md-4 mb-3">
                    <div class="position-relative form-group">
                        <label for="exampleEmail" class="">Email</label>
                    <input name="email" value="{{old('email')}}" id="exampleEmail" placeholder="Email" type="email" class="form-control" required>
                        </div>
                            @error('email')
                                <span style="color: red">{{$message}}</span>
                            @enderror
                </div>
            </div>

            <button class="btn btn-primary" type="submit">Salvar</button>

        </form>

        <script>
            // Example starter JavaScript for disabling form submissions if there are invalid fields
            (function() {
                'use strict';
                window.addEventListener('load', function() {
                    // Fetch all the forms we want to apply custom Bootstrap validation styles to
                    var forms = document.getElementsByClassName('needs-validation');
                    // Loop over them and prevent submission
                    var validation = Array.prototype.filter.call(forms, function(form) {
                        form.addEventListener('submit', function(event) {
                            if (form.checkValidity() === false) {
                                event.preventDefault();
                                event.stopPropagation();
                            }
                            form.classList.add('was-validated');
                        }, false);
                    });
                }, false);
            })();
        </script>
    </div>
</div>


@endsection
@include('menu', ['atives' => ['func', 'create_func'],'menus' => ['m_func']])

@section('js_render')
<script>
    $(document).ready(function(){

        function getDistrict(id){

            $.ajax({
                'url': '/employees/getprovincia/' + id,
                'method': 'get',
                'dataType': 'json',

                success:function(data){

                    if(data.success == true){

                        $('#getdistrict').html('');
                        $('#getdistrict').append('<option>Seleccione o Distrito</option>');

                        var x = data.data.length;
                        var output = '';
                        for (let index = 0; index < x; index++) {
                          output += '<option value="'+data.data[index].nome+'">'+data.data[index].nome+'</option>';
                        }

                        $('#getdistrict').append(output);
                    }
                },
                error:function(data){
                    alert('erro');
                }
            });
        }


        $('#province_id').on('change' , function(){
            var id = $(this).val();
            getDistrict(id);
        });


    });
</script>
@endsection

resources/views/admin/employee/edit.blade.php
@extends('layouts.admin')


@section('content')

<div class="main-card mb-3 card">
    <div class="card-body">
       <h5>Fucionario</h5>
        <form class="needs-validation" novalidate method="POST" action="{{ route('employees.update', [$employee->id]) }}">
            @csrf
            @method('PUT')
            <div class="form-row">
                <div class="col-md-4 mb-3">
                    <label for="validationCustom01">Nome Completo</label>
                <input type="text" class="form-control" id="validationCustom01" name="nome" value="{{$employee->nome ?? ''}}" placeholder="Nome Completo" required>
                 </div>
                <div class="col-md-4 mb-3">
                    <label for="validationCustom02">Apelido</label>
                    <input type="text" class="form-control" id="validationCustom02" value="{{$employee->apelido ?? ''}}"  name ="apelido" placeholder="Apelido" required>
                </div>
                <div class="col-md-4 mb-3">
                    <label for="validationCustomUsername">Data de nascimento</label>
                    <div class="input-group">
                        <input type="date" class="form-control" id="validationCustomUsername" value="{{$employee->data_nascimento ?? ''}}" name="data_nascimento" required>
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <div class="position-relative form-group"><label for="exampleSelect" class="">Provincia de nascimento</label>
                        <select name="provincia_nascimento" id="province_id" class="form-control">
                            <option>Provincia</option>
                            @foreach ($provinces as $province)
                                <option value="{{$province->id}}-{{$province->nome}}">{{$province->nome}}</option>
                            @endforeach
                        </select>
                        <div class="invalid-feedback">
                            Please provide a valid Provincia de nascimento.
                        </div>
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <div class="position-relative form-group"><label for="exampleSelect" class="">Distrito de nascimento</label>
                        <select name="distrito_nascimento" id="getdistrict" class="form-control" required>

                        </select>
                        <div class="invalid-feedback">
                            Please provide a valid Distrito de nascimento.
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-6 mb-3">
                    <label for="validationCustom03">Nacionalidade</label>
                    <input type="text" class="form-control" id="validationCustom03" value="{{$employee->nacionalidade ?? ''}}" name="nacionalidade" placeholder="Nacionalidade" required>
                 </div>
                <div class="col-md-3 mb-3">
                    <label for="validationCustom03">Sexo</label>
                    <input type="text" class="form-control" id="validationCustom03" value="{{$employee->sexo ?? ''}}" name="sexo" placeholder="Nacionalidade" required>
                </div>
                <div class="col-md-3 mb-3">
                    <label for="validationCustom05">BI Nº</label>
                    <input type="text" class="form-control" id="validationCustom05" value="{{$employee->nr_bi ?? ''}}" name="nr_bi" placeholder="Numero de BI" required>
                    <div class="invalid-feedback">
                        Please provide a valid BI.
                    </div>
                </div>
                <div class="col-md-3 mb-3">
                    <label for="validationCustom05">Passaporte Nº</label>
                    <input type="text" class="form-control" id="validationCustom05" value="{{$employee->nr_passaporte ?? ''}}" name="nr_passaporte" placeholder="Numero de Passaporte" required>

                </div>
                <div class="col-md-3 mb-3">
                    <label for="validationCustom05">Nuit Nº</label>
                    <input type="text" class="form-control" id="validationCustom05" value="{{$employee->nr_nuit ?? ''}}" name="nr_nuit" placeholder="Numero de Nuit" required>

                </div>
                <div class="col-md-3 mb-3">
                    <label for="validationCustom05">Contacto</label>
                    <input type="text" class="form-control" id="validationCustom05" value="{{$employee->contacto ?? ''}}" name="contacto" placeholder="Numero de Contacto" required>

                </div>
                <div class="col-md-3 mb-3">
                    <div class="position-relative form-group">
                        <label for="exampleEmail" class="">Email</label>
                        <input name="email" id="exampleEmail" value="{{$employee->email ?? ''}}" type="email" class="form-control">
                    </div>

                </div>
            </div>
            {{-- <div class="form-group">
                <div>
                    <label class="form-check-label" for="invalidCheck">
                        Voltar
                    </label>

                </div>
            </div>
            <a href="" class="btn btn-info btn-sm">
                <i class="fa fa-arrow-left"></i>
            </a> --}}
            <button  class="btn btn-primary" type="Voltar">Editar</button>
        </form>
     </div>
</div>

@endsection
@include('menu', ['atives' => ['func', 'index_func'],'menus' => ['m_func']])

@section('js_render')
<script>
    $(document).ready(function(){

        function getDistrict(id){

            $.ajax({
                'url': '/employees/getprovincia/' + id,
                'method': 'get',
                'dataType': 'json',

                success:function(data){

                    if(data.success == true){

                        $('#getdistrict').html('');
                        $('#getdistrict').append('<option>Seleccione o Distrito</option>');

                        var x = data.data.length;
                        var output = '';
                        for (let index = 0; index < x; index++) {
                          output += '<option value="'+data.data[index].nome+'">'+data.data[index].nome+'</option>';
                        }

                        $('#getdistrict').append(output);
                    }
                },
                error:function(data){
                    alert('erro');
                }
            });
        }


        $('#province_id').on('change' , function(){
            var id = $(this).val();
            getDistrict(id);
        });


    });
</script>
@endsection

resources/views/admin/employee/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="main-card mb-3 card">
    <div class="card-body"><h5 style = "margin-bottom:2%;" class="card-title">Funcionarios</h5>
        <div class="table-responsive">
            @csrf
            <table class="mb-0 table table-hover">
                <thead class="thead-dark">
                <tr>
                    <th>id</th>
                    <th>nome</th>
                    <th>nacionalidade</th>
                    <th>sexo</th>
                    <th>contacto</th>
                    <th>email</th>
                    <th>Operação</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($employee as $employees)
                    <tr>
                        <th scope="row">{{$employees->id}}</th>
                        <td>{{$employees->nome}}</td>
                        <td>{{$employees->nacionalidade}}</td>
                        <td>{{$employees->sexo}}</td>
                        <td>{{$employees->contacto}}</td>
                        <td>{{$employees->email}}</td>
                        <td>
                            <a href="{{route('employees.show', $employees->id)}}" class="btn btn-info btn-sm">
                                <i class="fas fa-eye"></i>
                            </a>
                            <a href="{{route('employees.edit', $employees->id)}}" class="btn btn-warning btn-sm">
                                <i class="fas fa-pen"></i>
                            </a>
                            <a href="{{route('employees.destroy', $employees->id)}}" class="btn btn-danger btn-sm btn-del">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>
</div>
@endsection

@include('menu', ['atives' => ['func', 'index_func'],'menus' => ['m_func']])

@section('js_render')
<script>

  (function (win,doc) {

      function confirmDel(event) {

          event.preventDefault();
          //console.log(event.target.parentNode.href);
           let token = doc.getElementsByName("_token")[0].value;
           if(confirm("Deseja mesmo apagar?")){
            let ajax = new XMLHttpRequest();
            ajax.open("DELETE",event.target.parentNode.href);
               ajax.setRequestHeader('X-CSRF-TOKEN',token);
               ajax.onreadychange = function(){
                     if(ajax.readyState === 4 && ajax.status === 200){
                        win.location.href ="";

                     }
               };
               ajax.send();


           }else{
                return false;
           }
      }
      if(doc.querySelector('.btn-del')){
          let btn = doc.querySelectorAll('.btn-del');
          for(let i=0; i<btn.length; i++){
              btn[i].addEventListener('click',confirmDel,false);
          }

      }
  })(window,document);

</script>
@endsection

resources/views/home.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@include('menu', ['atives' => ['home'],'menus' => []])

resources/views/includes/404.blade.php
	<link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,700" rel="stylesheet">
<style>
  * {
  -webkit-box-sizing: border-box;
          box-sizing: border-box;
}

body {
  padding: 0;
  margin: 0;
}

#notfound {
  position: relative;
  height: 80vh;
}

#notfound .notfound {
  position: absolute;
  left: 50%;
  top: 40%;
  -webkit-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
          transform: translate(-50%, -50%);
}

.notfound {
  max-width: 520px;
  width: 100%;
  line-height: 1.4;
  text-align: center;
}

.notfound .notfound-404 {
  position: relative;
  height: 200px;
  margin: 0px auto 20px;
  z-index: -1;
}

.notfound .notfound-404 h1 {
  font-family: 'Montserrat', sans-serif;
  font-size: 236px;
  font-weight: 200;
  margin: 0px;
  color: #211b19;
  text-transform: uppercase;
  position: absolute;
  left: 50%;
  top: 50%;
  -webkit-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
          transform: translate(-50%, -50%);
}

.notfound .notfound-404 h2 {
  font-family: 'Montserrat', sans-serif;
  font-size: 28px;
  font-weight: 400;
  text-transform: uppercase;
  color: #211b19;
  background: #fff;
  padding: 10px 5px;
  margin: auto;
  display: inline-block;
  position: absolute;
  bottom: 0px;
  left: 0;
  right: 0;
}

.notfound a {
  font-family: 'Montserrat', sans-serif;
  display: inline-block;
  font-weight: 700;
  text-decoration: none;
  color: #fff;
  text-transform: uppercase;
  padding: 13px 23px;
  background: #ff6300;
  font-size: 18px;
  -webkit-transition: 0.2s all;
  transition: 0.2s all;
}

.notfound a:hover {
  color: #ff6300;
  background: #211b19;
}

@media only screen and (max-width: 767px) {
  .notfound .notfound-404 h1 {
    font-size: 148px;
  }
}

@media only screen and (max-width: 480px) {
  .notfound .notfound-404 {
    height: 148px;
    margin: 0px auto 10px;
  }
  .notfound .notfound-404 h1 {
    font-size: 86px;
  }
  .notfound .notfound-404 h2 {
    font-size: 16px;
  }
  .notfound a {
    padding: 7px 15px;
    font-size: 14px;
  }
}

</style>

<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>Oops!</h1>
				<h2>404 - The Page can't be found</h2>
			</div>
			<a href="{{ url('/') }}">Go TO Homepage</a>
			
		</div>
	</div>

resources/views/menu.blade.php
@push('menus')


<li class="nav-item">
    <a href="{{ route('home') }}" class="nav-link home">
        <i class="nav-icon fas fa-home"></i>
        <p>
            Dashboard
            {{-- <span class="right badge badge-danger">New</span> --}}
        </p>
    </a>
</li>
<li class="nav-item has-treeview m_func">
    <a href="#" class="nav-link func">
        <i class="nav-icon fas fa-users"></i>
        <p>
            Funcionarios
            <i class="fas fa-angle-left right"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="{{ route('employees.create') }}" class="nav-link create_func">
                <i class="fas fa-plus-circle nav-icon"></i>
                <p>Adicionar Funcionarios</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('employees.index') }}" class="nav-link index_func">
                <i class="fas fa-list nav-icon"></i>
                <p>Listar Funcionarios</p>
            </a>
        </li>

    </ul>
</li>


@endpush
@push('script')

<script>
    @foreach ($atives as $ative)
        $('.' + '{{ $ative }}').addClass('active')
    @endforeach
    @foreach ($menus as $ative)
    $('.' + '{{ $ative }}').addClass('menu-open')
    @endforeach
</script>
@endpush